### ISSUE TITLE
Using Jenkins HelloWorld did not generate observation data.

### ISSUE THREAD

**Issue by wajika** [jenkinsci/opentelemetry-plugin#348]
I use helloworld to test on a newly deployed jenkins, this is my first operation, I don't know right or wrong.
After the build I click "View pipeline with Elastic Observability", the browser goes into kibana, but I don't see any data.
I suspect helloworld is not suitable for testing opentelemetry.
We use dotnet language development, that is, do not use maven and Gradle, so is there any simple case to test?

 I've had some comments here [301](https://github.com/jenkinsci/opentelemetry-plugin/issues/301#issuecomment-1055169690)

![image](https://user-images.githubusercontent.com/17058349/156140807-008d6963-3b3b-4710-867a-84f2555d4c7c.png)
![image](https://user-images.githubusercontent.com/17058349/156140822-a2e2e08d-a7f0-401d-b69f-c7e5f6c25e5c.png)
![image](https://user-images.githubusercontent.com/17058349/156140830-edd86243-ce95-473d-83ee-cff4ab2effba.png)
![image](https://user-images.githubusercontent.com/17058349/156140932-455cc05b-4146-4a19-9cb6-823537ac0de3.png)

I don't think this issue should be a bug, so I filed this issue with a blank.

update 2

jenkins info
```
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
```

opentelemetry points directly to elastic apmserver
![image](https://user-images.githubusercontent.com/17058349/156149027-fd7a564b-8b30-4f9f-a1db-850e83340d2f.png)

elastic stack version : 7.16.3
jenkins is newly installed and its plugins are the latest version.
