### ISSUE TITLE
Exporting pipeline logs to backends other than elastic 

### ISSUE THREAD

**Issue by vlad-ivanov-name** [jenkinsci/opentelemetry-plugin#478]
### Describe your use-case which is not covered by existing documentation.

Hello, first of all thanks for the awesome plugin! It solves a lot of problems when it comes to observability in Jenkins.

I have a question, the page "Build Logs" mentions that pipeline logs can be stored in backends other than elastic:

https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/build-logs.md#can-pipeline-logs-be-stored-in-other-backends-than-elastic

But how to set that up? I have an otel-collector instance running with the following config:

<details>
<summary><code>otel-config.yml</code></summary>

```yml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "*"

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  resourcedetection:
    detectors: [gcp]
    timeout: 10s

exporters:
  logging:
    logLevel: info
  googlecloud:
    retry_on_failure:
      enabled: false
    log:
      default_log_name: otel-collector

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud]
```
</details>

I don't see any errors but I also don't see any logs. It's not clear to me if pipeline logs are pushed to the OTLP endpoint by default; when setting up a "Custom Observability Backend", there is no choice given as to where the pipeline logs should be stored.

Would it be possible to clarify this in documentation?

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

_See above_
