### ISSUE TITLE
customObservabilityBackend for logs

### ISSUE THREAD

**Issue by chewrocca** [jenkinsci/opentelemetry-plugin#721]
### What feature do you want to see added?

Currently there is customObservabilityBackend for Traces and Metrics.  Please consider adding one for Logs.

```sh
    observabilityBackends:
    - customObservabilityBackend:
        metricsVisualizationUrlTemplate: "foo"
        traceVisualisationUrlTemplate: "http://example.com"
        name: "Custom Observability"
```

**Comment by cyrille-leclerc** [comment]
This would be a great enhancement. Out of curiosity, what would be the backend please?

**Comment by chewrocca** [comment]
We planned to use Grafana Loki.

**Comment by cyrille-leclerc** [comment]
I have started working on a Loki integration. I'll open a draft PR soon to make the progess visible and welcome contributions.

**Comment by cyrille-leclerc** [comment]
Please see:
* https://github.com/jenkinsci/opentelemetry-plugin/pull/727

**Comment by cyrille-leclerc** [comment]
@chewrocca can you please test Loki storage added by https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-2.18.0-beta1

**Comment by cyrille-leclerc** [comment]
Grafana Loki support fixed in https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-2.18.0-beta1

We will reopen the topic of a generic CustomObservabilityBackend when the new use case comes so we can see if existing capabilities are generic enough.

**Comment by chewrocca** [comment]
@cyrille-leclerc These changes work great.  Thank you!

Should I open a PR to add the configuration examples for the Grafana backend?

```
    observabilityBackends:
    - grafana:
        grafanaBaseUrl: "https://example.grafana.net"
        tempoDataSourceIdentifier: "grafanacloud-traces"
        tempoQueryType: "traceql"
        grafanaOrgId: "1"
        name: "Grafana"
        grafanaLogsBackend:
          GrafanaLogsBackendWithoutJenkinsVisualization:
            grafanaLokiDatasourceIdentifier: "grafanacloud-logs"
```

What is the option for `grafanaMetricsDashboard `?  I'm curious about what this configuration does.  I didn't enable it. 

Is it possible to avoid confusion by ignoring the "View as plain text" under Console Output?  That link didn't do anything once the Grafana Logs were set up.
